### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by talantbekov123** [glpsch/RegExp.github.io#1]
Хорошая работа! Почти все основные требования выполнены, похвально что учли знаки "-" и "." для email! Почти нет проблем с валидацией, есть версионность!

Прошу исправить комментарии надо исправить что бы я мог принять работу.
**Надо исправить**
- “http://some.test.yandex.ru” не проходят валидацию адреса с поддоменами.
- "http://google.ru///1///2///3" (количество слешей в пути должно быть ограничено одним экземпляром для каждой части пути)
- Проверку проходит следующий некорректный адре сайта http://ya.ru:00000, http://11.11.11.11:0000 (в IPv4 порт это целое число равное максимум 65535, так как это целое число, то несколько нулей подряд являются невалидными). Подробнее про порты можно почитать [тут](https://buy.fineproxy.org/articles/chto-takoe-port-servera.html)
- Не полностью заполнен readme. В оформленном readme.md должна быть проставленная версия, есть заголовок, **ссылка на проект работающий на github pages.**

**Можно лучше**
- файлы logo.svg и cover.jpg, расположенные в репозитории не используются на странице (загружаются с серверов Яндекса). Просьба либо задействовать их либо удалить.
- Добавьте .gitignore, содержащий правила, исключающие попадание временных и\или системных файлов в репозиторий.

**Comment by glpsch** [comment]
Учла все замечания, за исключением .gitignore, поскольку, кажется, в папке сейчас не лежит ничего, что необходимо было бы проигнорировать.

**Comment by talantbekov123** [comment]
Отличная работа! Все исправлено!

**Похвально**
- эфективное регулярное выражение
- оформленное readme.md
- работа на github pages, все поля работают
- нет лишних файлов в репозитории
- требования к веткам соблюдены
- в поле url реализованы все проверки (ip, dns, http/s)

В .gitignore можно было бы добавить файлы .png, .svg что бы в будущем случайно медиа файлы в проект не попали. А комментарий добавил, так как в следующей практической работе .gitignore обязателен, что бы вас немного подготовить. В целом отличная работа, вы молодец!
